      PROGRAM CH0601
      IMPLICIT LOGICAL (A-Z)
C
C EXAMPLE OF A FORTRAN PROGRAM TO CALCULATE NET PAY
C GIVEN AN EMPLOYEE'S GROSS PAY
C
      REAL GROSS, NET, TAX
      REAL TAXRAT
      INTEGER PA
      CHARACTER*60 PNAME
         TAXRAT=0.25
         PA=4800
         PRINT *,'INPUT EMPLOYEES NAME'
         READ *,PNAME
         PRINT *,'INPUT GROSS WAGE'
         READ *,GROSS
         TAX = (GROSS - PA) * TAXRAT
         NET = GROSS - TAX
         PRINT *,'EMPLOYEE: ',PNAME
         PRINT *,'GROSS PAY: ', GROSS
         PRINT *,'TAX: ',TAX
         PRINT *,'NET PAY:',NET
      END