      PROGRAM CH0704
      IMPLICIT LOGICAL (A-Z)
C
C VARIABLES USED
C HEIGHT - USED TO HOLD THE HEIGHTS ABOVE SEA LEVEL
C LONGIT - USED TO REPRESENT THE LONGITUDE
C RESTRICTED TO INTEGER VALUES.
C LATUDE - USED TO REPRESENT THE LATITUDE
C AGAIN RESTRICTED TO INTEGER VALUES.
C CORECT - A CORRECTION FACTOR
      REAL HEIGHT
      REAL CORECT
      INTEGER LONGIT,LATUDE, N
      PARAMETER (CORECT=10.0, N=3)
      DIMENSION HEIGHT(N,N)
      DO 8 LATUDE=1,N
        DO 9 LONGIT=1,N
          PRINT*,'INPUT HEIGHT FOR LATUDE = ',LATUDE,' LONGIT = ',LONGIT
          READ*, HEIGHT(LATUDE, LONGIT)
          HEIGHT(LATUDE, LONGIT) = HEIGHT(LATUDE, LONGIT) + CORECT
 9      CONTINUE
 8    CONTINUE
      PRINT *,'CORRECTED VALUES ARE:'
      DO 10 LATUDE=1,N
        DO 11 LONGIT=1,N
          PRINT *,HEIGHT(LATUDE,LONGIT)
11      CONTINUE
10    CONTINUE
      END