      PROGRAM SUMAVE
      IMPLICIT LOGICAL (A-Z)
C
C THE PROGRAM READS UP TO 10 WEIGHTS INTO THE
C ARRAY WEIGHT
C VARIABLES USED
C N - NUMBER OF WEIGHTS
C WEIGHT, HOLDS THE WEIGHT OF THE PEOPLE
C PERSON, AN INDEX INTO THE ARRAY
C TOTAL, TOTAL WEIGHT
C AVERAG, AVERAGE OF THE WEIGHTS
C
C THE WEIGHTS ARE WRITTEN OUT SO THAT THEY CAN BE CHECKED
C UPDATED - N IS NOW A PARAMETER
C
      REAL WEIGHT,TOTAL,AVERAG
      INTEGER N,PERSON
      PARAMETER(N=10)
      DIMENSION WEIGHT(N)
        TOTAL=0.0
        PRINT *,'INPUT ',N,' WEIGHTS'
        DO 100 PERSON=1,N
          READ *,WEIGHT(PERSON)
          TOTAL = TOTAL + WEIGHT(PERSON)
100     CONTINUE
        AVERAG = TOTAL / N
        PRINT *,' SUM OF NUMBERS IS ',TOTAL
        PRINT *,' AVERAGE WEIGHT IS ',AVERAG
        PRINT *,N,' WEIGHTS WERE '
        DO 200 PERSON=1,N
          PRINT *,WEIGHT(PERSON)
200     CONTINUE
      END