      PROGRAM SUMAVE
      IMPLICIT LOGICAL (A-Z)
C
C THE PROGRAM READS UP TO 10 WEIGHTS INTO THE
C ARRAY WEIGHT
C VARIABLES USED
C WEIGHT, HOLDS THE WEIGHT OF THE PEOPLE
C PERSON, AN INDEX INTO THE ARRAY
C TOTAL, TOTAL WEIGHT
C AVERAG, AVERAGE OF THE WEIGHTS
C
C THE WEIGHTS ARE WRITTEN OUT SO THAT THEY CAN BE CHECKED
C
      REAL WEIGHT,TOTAL,AVERAG
      INTEGER PERSON
      DIMENSION WEIGHT(10)
        TOTAL=0.0
        PRINT *,'INPUT 10 WEIGHTS'
        DO 100 PERSON=1,10
          READ *,WEIGHT(PERSON)
          TOTAL = TOTAL + WEIGHT(PERSON)
100     CONTINUE
        AVERAG = TOTAL / 10
        PRINT *,' SUM OF NUMBERS IS ',TOTAL
        PRINT *,' AVERAGE WEIGHT IS ',AVERAG
        PRINT *,' 10 WEIGHTS WERE '
        DO 200 PERSON=1,10
          PRINT *,WEIGHT(PERSON)
200     CONTINUE
      END