      PROGRAM MEANSD
C
C VARIABLES USED ARE
C MEAN - FOR THE RUNNING MEAN
C SSQ - THE RUNNING CORRECTED SUM OF SQUARES
C X - INPUT VALUES FOR WHICH MEAN AND SD REQUIRED
C W - LOCAL WORK VARIABLE
C SD - STANDARD DEVIATION
C R - ANOTHER LOCAL WORK VARIABLE
C
      REAL MEAN,SSQ,X,W,SD,R
      INTEGER I
      MEAN=0.0
      SSQ=0.0
      PRINT *,' ENTER THE NUMBER OF READINGS'
      READ*,N
      PRINT*,' ENTER THE ',N,' VALUES, ONE PER LINE'
      DO 1 I=1,N
        READ*,X
        W=X-MEAN
        R=I-1
        MEAN=(R*MEAN+X)/I
        SSQ=SSQ+W*W*R/I
1     CONTINUE
      SD=(SSQ/R)**0.5
      PRINT *,' MEAN IS ',MEAN
      PRINT *,' STANDARD DEVIATION IS ',SD
      END