      PROGRAM CH0801
      DIMENSION CURRNT (-20:20)
      REAL CURRNT,RESIST
      INTEGER VOLTAG
        PRINT*,'INPUT RESISTANCE'
        READ*,RESIST
        DO 10 VOLTAG = -20,20
          CURRNT(VOLTAG)=VOLTAG/RESIST
          PRINT*,VOLTAG,' ',CURRNT(VOLTAG)
10      CONTINUE
      END