      PROGRAM CH0906
C THIS PROGRAM READS IN AND PRINTS OUT
C YOUR FIRST NAME
      IMPLICIT LOGICAL (A-Z)
      CHARACTER*20 FNAME
        PRINT *, ' TYPE IN YOUR FIRST NAME.'
        PRINT *, ' UP TO 20 CHARACTERS'
        READ *, FNAME
        PRINT 100, FNAME
 100    FORMAT (1X,A)
      END PROGRAM CH0906