      PROGRAM QROOTS
      REAL A,B,C,TERM,A2,ROOT1,ROOT2
C
C A B AND C ARE THE COEFFICIENTS OF THE TERMS
C A*X**2+B*X+C
C FIND THE ROOTS OF THE QUADRATIC, ROOT1 AND ROOT2
C
      PRINT*,' GIVE THE COEFFICIENTS A, B AND C'
      READ*,A,B,C
      TERM = B*B - 4.*A*C
      A2 = A*2.
C IF TERM < 0, ROOTS ARE COMPLEX
C IF TERM = 0, ROOTS ARE EQUAL
C IF TERM > 0, ROOTS ARE REAL AND DIFFERENT
      IF(TERM.LT.0.0)THEN
        PRINT*,' ROOTS ARE COMPLEX'
      ELSEIF(TERM.GT.0.0)THEN
        TERM = TERM**0.5
        ROOT1 = (-B+TERM)/A2
        ROOT2 = (-B-TERM)/A2
        PRINT*,' ROOTS ARE ',ROOT1,' AND ',ROOT2
      ELSE
        ROOT1 = -B/A2
        PRINT*,' ROOTS ARE EQUAL, AT ',ROOT1
      ENDIF
      END