      PROGRAM C1304A
      REAL RESULT,PI,N,R
      PARAMETER (PI=3.14159265358)
C STIRL CALCULATES AN APPROXIMATION TO N! FOR LARGE N
      STIRL(X)=SQRT(2.*PI)*X**(X+0.5)*EXP(-X)
      N=10.
      R=7.
C NUMBER OF POSSIBLE COMBINATIONS THAT CAN BE FORMED WHEN
C R OBJECTS ARE SELECTED OUT OF A GROUP OF N
C N!/(R!(N-R)!)
      RESULT=STIRL(N)/(STIRL(R)*STIRL(N-R))
      PRINT *,'FOR N =',N
      PRINT *,'R = ',R
      PRINT*,'NUMBER OF COMBINATIONS WHEN ',R,' OBJECTS'
      PRINT*,'ARE SELECTED OUT OF A GROUP OF ',N
      PRINT*,'IS ',RESULT
      END