      PROGRAM C1701A
      IMPLICIT LOGICAL(A-Z)
      CHARACTER*80 STRING, STRIP
      INTEGER IPOS,I,LEN
      PRINT*,'INPUT A PHRASE OR SENTENCE (MAX 80 CHARS)'
      READ(UNIT=5,FMT='(A)')STRING
      IPOS=0
      LEN=80
      STRIP=' '
      DO 1 I=1,LEN
         IF(STRING(I:I).NE.' ') THEN
            IPOS=IPOS+1
            STRIP(IPOS:IPOS)=STRING(I:I)
         ENDIF
1     CONTINUE
      PRINT*,'ORIGINAL:'
      PRINT*,STRING
      PRINT*,'WITH BLANKS REMOVED:'
      PRINT*,STRIP
      END