      PROGRAM C1901A
      REAL X
      CHARACTER*20 WHICH
1     WRITE(UNIT=6,FMT='('' DATA SET NAME, OR END'')')
      READ(UNIT=5,FMT='(A)') WHICH
      IF(WHICH.EQ.'END') STOP
      OPEN(UNIT=1,FILE=WHICH)
      READ(UNIT=1,FMT=100) X
100   FORMAT(F7.2)
      WRITE(UNIT=6,FMT=200)WHICH,X
200   FORMAT(1X,'FROM FILE ',A,' VALUE OF X = ',F7.2)
      CLOSE(UNIT=1)
      GO TO 1
      END